<a href="https://colab.research.google.com/github/Shivxnshjasathi/BetterHire/blob/main/employees_suggestion_system.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
resume_data = pd.read_csv("/content/Resume_data.csv")
resume_data

    Exp  Skills      Name
0     2       1       Ram
1     3       3  Shivansh
2     5       5    travis
3     4       2    mukesh
4     5       5      Jack
5     4       3    vedant
6     1       6       May
7     3       2      Alex
8     7       6      yash
9     2       1    anchal
10    1       6      duke
11    5       4     virat
12    2       3    michal
13    7       4       sam
14    0       4       Amy
15    1       1      joey
16    4       3     penny
17    5       2      tony

In [2]:
x = resume_data.drop(columns=['Name'])
x

    Exp  Skills
0     2       1
1     3       3
2     5       5
3     4       2
4     5       5
5     4       3
6     1       6
7     3       2
8     7       6
9     2       1
10    1       6
11    5       4
12    2       3
13    7       4
14    0       4
15    1       1
16    4       3
17    5       2

In [3]:
y = resume_data['Name']
y

0          Ram
1     Shivansh
2       travis
3       mukesh
4         Jack
5       vedant
6          May
7         Alex
8         yash
9       anchal
10        duke
11       virat
12      michal
13         sam
14         Amy
15        joey
16       penny
17        tony
Name: Name, dtype: object

In [10]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.1)
x.shape,x_train.shape, x_test.shape

((18, 2), (16, 2), (2, 2))

In [15]:
from sklearn.tree import DecisionTreeClassifier
model = DecisionTreeClassifier()
model.fit(x_train, y_train)

DecisionTreeClassifier()

In [16]:
predictions = model.predict([[3,1],[0,5]])
predictions

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(

array(['anchal', 'Amy'], dtype=object)